HOSTS:
  debian-76-x64:
    roles:
      - master
    platform: debian-7-amd64
    box: fgrehm/wheezy64-lxc
    box_url: https://vagrantcloud.com/fgrehm/boxes/wheezy64-lxc
    hypervisor: vagrant
    ip: '10.0.3.20'
CONFIG:
  log_level: verbose
  type: git