#!/bin/bash
set -eux

. "$(dirname "$(readlink -f "$0")")"/functions.sh

ARCHIVE_MODULE_URL="https://forge.puppet.com/v3/files/puppet-archive-1.0.0.tar.gz"
JAVA_MODULE_URL="https://forge.puppet.com/v3/files/puppetlabs-java-1.6.0.tar.gz"
STDLIB_MODULE_URL="https://forge.puppet.com/v3/files/puppetlabs-stdlib-4.12.0.tar.gz"
SYSTEMD_MODULE_URL="https://forge.puppet.com/v3/files/camptocamp-systemd-0.2.2.tar.gz"
ZOOKEEPER_MODULE_URL="https://forge.puppet.com/v3/files/deric-zookeeper-0.5.5.tar.gz"
KAFKA_MODULE_URL="https://forge.puppet.com/v3/files/puppet-kafka-2.0.0.tar.gz"

download_puppet_module "archive"    "${ARCHIVE_MODULE_URL}"
download_puppet_module "java"       "${JAVA_MODULE_URL}"
download_puppet_module "stdlib"     "${STDLIB_MODULE_URL}"
download_puppet_module "systemd"    "${SYSTEMD_MODULE_URL}"
download_puppet_module "zookeeper"  "${ZOOKEEPER_MODULE_URL}"
download_puppet_module "kafka"      "${KAFKA_MODULE_URL}"

# Patching modules
PATCH_DIR="deployment_scripts/puppet/patches"
MODULES_DIR="deployment_scripts/puppet/modules"
cp -f $PATCH_DIR/zookeeper/manifests/post_install.pp       $MODULES_DIR/zookeeper/manifests
cp -f $PATCH_DIR/zookeeper/manifests/service.pp            $MODULES_DIR/zookeeper/manifests
cp -f $PATCH_DIR/zookeeper/templates/conf/zoo.cfg.erb      $MODULES_DIR/zookeeper/templates/conf
cp -f $PATCH_DIR/zookeeper/templates/conf/environment.erb  $MODULES_DIR/zookeeper/templates/conf
cp -f $PATCH_DIR/zookeeper/templates/zookeeper.service.erb $MODULES_DIR/zookeeper/templates/
cp -f $PATCH_DIR/kafka/manifests/init.pp                   $MODULES_DIR/kafka/manifests
cp -f $PATCH_DIR/kafka/manifests/broker/service.pp         $MODULES_DIR/kafka/manifests/broker
cp -f $PATCH_DIR/kafka/templates/init.erb                  $MODULES_DIR/kafka/templates
cp -f $PATCH_DIR/kafka/templates/broker.unit.erb           $MODULES_DIR/kafka/templates

KAFKA_TARBALL_URL="http://mirrors.ukfast.co.uk/sites/ftp.apache.org/kafka/0.10.0.0/kafka_2.11-0.10.0.0.tgz"
download_file "${KAFKA_TARBALL_URL}" kafka_2.11-0.10.0.0.tgz repositories/ubuntu/kafka/0.10.0.0
